before_install:
  - openssl aes-256-cbc -K $encrypted_4ed337f84da7_key -iv $encrypted_4ed337f84da7_iv -in secring.gpg.enc -out secring.gpg -d

sudo: false
language: java
jdk:
  - oraclejdk8

install: true
script: if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./gradlew build uploadArchives; else ./gradlew build; fi

before_cache:
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
